nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
