services:
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: development
    command: yarn start:dev api-gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - .env

  conversation-service:
    image: conversation-service
    build:
      context: .
      dockerfile: apps/conversation-service/Dockerfile
      target: development
    command: yarn start:dev conversation-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - apps/conversation-service/.env
      - .env

  message-service:
    image: message-service
    build:
      context: .
      dockerfile: apps/message-service/Dockerfile
      target: development
    command: yarn start:dev message-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

  upload-service:
    image: upload-service
    build:
      context: .
      dockerfile: apps/upload-service/Dockerfile
      target: development
    command: yarn start:dev upload-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
    env_file:
      - apps/upload-service/.env
      - .env

  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      target: development
    command: yarn start:dev auth-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
