services:
  channel-service:
    build:
      context: .
      dockerfile: apps/channel-service/Dockerfile
      target: production
    command: node dist/apps/channel-service/main
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    env_file:
      - apps\channel-service\.env
  mongo:
      image: mongo

      