services:
  api-gateway:
    image: r0tc1v/api-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: production
    command: yarn start:dev api-gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - .env

  conversation-service:
    image: r0tc1v/conversation-service
    build:
      context: .
      dockerfile: apps/conversation-service/Dockerfile
      target: production
    command: yarn start:dev conversation-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3004
    env_file:
      - apps/conversation-service/.env
      - .env

  message-service:
    image: r0tc1v/message-service
    build:
      context: .
      dockerfile: apps/message-service/Dockerfile
      target: production
    command: yarn start:dev message-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3005:3005
    env_file:
      - .env

  upload-service:
    image: r0tc1v/upload-service
    build:
      context: .
      dockerfile: apps/upload-service/Dockerfile
      target: production
    command: yarn start:dev upload-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
    env_file:
      - apps/upload-service/.env
      - .env

  auth-service:
    image: r0tc1v/auth-service
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      target: production
    command: yarn start:dev auth-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
    env_file:
      - .env
