apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channels
  template:
    metadata:
      labels:
        app: channels
    spec: 
      containers:
        - name: channels
          image: 851725474122.dkr.ecr.ap-southeast-1.amazonaws.com/channels:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: mongodb+srv://tboost:bJyQ6wlOlH4wmKAA@tboost.yfn92k6.mongodb.net/?retryWrites=true&w=majority&appName=Tboost